name: Suggestion
description: Suggest an feature for RivertonRP
title: "[IDEA]: "
labels: ["Idea", "s: pending", "e: none"]

body:
  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Confirm all of these are checked and valid.
      options:
        - label: I have read and agree to the README (found on https://github.com/RivertonRP/Meta/blob/master/README.md)
          required: true
        - label: I am NOT reporting a security vulnerability
          required: true
        - label: I have searched the Issue Tracker to make sure this is not a duplicate issue
          required: true
        - label: This issue does not contain any sensitive information
          required: true
  - type: textarea
    id: idea
    attributes:
      label: What is your super amazing, awesome, fantastic, must have idea?
      description: Your feature suggestion should include a clear concise description of the feature.
    validations:
      required: true
  - type: textarea
    id: howuse
    attributes:
      label: How does this help people do amazing things?
      description: Who does the feature benefit? How is it useful to people?
    validations:
      required: true
